name: "dataUpdate"

on:
  schedule:
    - cron: '50 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Data
      run: sh ./script/make_current_member.sh
