name: "dataUpdate"

on:
  schedule:
    - cron: '20 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Update Data
      run: sh ./script/make_current_member.sh
    - name: setting git
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "KamekureMaisuke"
        git add .
        git commit -m "update current_data $(date '+%Y%m%d')"
        git push origin master
